name: unit-test
run-name: ${{ github.actor }} tests new push
on: [push]

jobs:
  test-on-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # python-version: ["3.10", "3.11", "3.12"]
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: | 
          pip install pytest pytest-cov pytest-github-report
          pytest -s --github-report --junitxml=junit/test-results.xml --cov=neptune_wrapper --cov-report=html
      - name: Coverage comment
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ github.token }}

  # test-on-windows:
  #   runs-on: windows-latest
  #   strategy:
  #     matrix:
  #       python-version: ["3.10", "3.11"]
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Setup Python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: ${{ matrix.python-version }}
  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install -r requirements.txt
  #     - name: Test with pytest
  #       run: |
  #         pip install pytest
  #         pytest --junitxml=junit/test-results.xml
