name: neptune_wrapper CI

run-name: ${{ github.actor }} tests new push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]
        exclude:
          - os: windows-latest
            python-version: 3.12
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest on ubuntu + coverage
        if : matrix.os == 'ubuntu-latest'
        run: |
          pip install pytest pytest-cov pytest-github-report
          pytest --github-report --junitxml=junit/test-results.xml --cov=neptune_wrapper --cov-report=html
      - name: Test with pytest on windows
        if : matrix.os == 'windows-latest'
        run: |
          pip install pytest
          pytest --junitxml=junit/test-results.xml
      - name: Coverage comment
        if: matrix.os == 'ubuntu-latest'
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ github.token }}

  check:
    if: always()
    needs:
    - test
    runs-on: ubuntu-latest
    steps:
    - name: Decide whether all tests and notebooks succeeded
      uses: re-actors/alls-green@release/v1
      with:
        jobs: ${{ toJSON(needs) }}
